name: saveBingWallPaer
on:
  schedule:
    - cron:  '30 6 * * *'
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: setup nodejs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: run node dome
        run: |
          npm install axios
          node .\bingwallpaper.js

